### PR TITLE
Allow users to omit packages

### PR DESCRIPTION
**Pull request by cryptodev-2s**
This PR allows users to omit packages from the release spec that have changes since their previous release to make it possible to make partial releases.

Issue: [92](https://github.com/MetaMask/create-release-branch/issues/92)

### CODE REVIEW

**Comment by Gudahtt** [comment]
@legobeat Thanks, good idea, I have approved your other PR. But I still think we need something like this PR to make the process for omitting packages easier.

Originally we had internationally added friction to dissuade people from omitting packages because omitting packages can be hazardous in ways that are easy to miss. But #90 and #91 should make the process a lot safer. After those are resolved, we want to make partial releases a low-friction process. Typing `intentionally-skip` 12 times isn't quite low friction enough to make this a pleasant tool to use.

I would suggest putting this on hold until after #90 and #91 are resolved, then merging this or something like it. We can consider alternative approaches to this PR as well, so long as they also achieve the goal of making partial releases low-friction.

**Comment by mcmire** [comment]
Given Mark's comment, does it make sense to mark this ticket as being blocked in some way?

**Comment by cryptodev-2s** [comment]
> Given Mark's comment, does it make sense to mark this ticket as being blocked in some way?

it's currently marked as blocked by 90 and 91 which there's two PRs waiting for review

**Comment by mcmire** [comment]
Okay, I've marked it as such using Zenhub.

**Comment by cryptodev-2s** [comment]
@legobeat PR updated now intentionally-skip is mandatory only when a package is used by another package or uses a package not on the release spec

**Review by mcmire — APPROVED** [review]
Looks good to me!

**Pull request merged**
